import torch
import torch.nn as nn
import torch.nn.functional as F
from torch_scatter import scatter_sum, scatter_max
from src.config.heuristics import HeuristicConfig

class HeuristicsEngine(nn.Module):
    """
    Slot X: HeuristicsEngine (Tensor-based Soft Bias Injection)
    
    This module implements differentiable heuristic rules that operate directly on 
    the virtual edge tensors (STT, Type, Time). It provides soft biases to 
    guide the Navigator (Exploration) and Reasoner (Verification).
    
    Design Philosophy:
    - Pure Tensor Operations: No loops, fully parallelizable.
    - Soft Bias: Injected as logits modifiers, preserving gradient flow.
    - Time-Aware: Dynamically adapts to t_sim and delta_t.
    """
    def __init__(self, cfg: HeuristicConfig):
        super().__init__()
        self.cfg = cfg
        
        # Learnable (or Fixed) Parameters
        # Using nn.Parameter allows the model to fine-tune the strength of heuristics
        # But we initialize them with config values.
        
        # Reasoner Heuristics
        self.lambda_suppress = nn.Parameter(torch.tensor(cfg.suppression_lambda), requires_grad=False)
        self.epsilon_suppress = cfg.suppression_epsilon
        
        # Navigator Heuristics
        self.lambda_wave = nn.Parameter(torch.tensor(cfg.wave_front_lambda), requires_grad=False)
        self.sigma_wave = cfg.wave_front_sigma
        
        self.lambda_hub = nn.Parameter(torch.tensor(cfg.hub_attractor_lambda), requires_grad=False)

    def forward(self):
        """No-op. Use specific computation methods."""
        pass

    def compute_reasoner_penalty(self, h_node, edge_index, edge_attr, t_sim, batch_idx):
        """
        Scheme 1: Time-Aware Clean Path Suppression
        
        Logic:
        For every negative anchor v (Type=-1), we look at upstream nodes u.
        If water should have reached v from u (STT < delta_t) but v is clean, 
        then u is unlikely to be the source.
        
        Penalty = ReLU( (t_sim - t_anchor) - STT * (1 + epsilon) )
        """
        if not self.cfg.enable_time_aware_suppression:
            return torch.zeros(h_node.size(0), device=h_node.device)
            
        # Extract Virtual Edge Attributes
        # edge_attr is 7D. Ch3=STT, Ch4=AnchorTime, Ch6=AnchorType
        # Virtual edges are those with AnchorType != 0?
        # Actually, all edges in 'curr_edge_index' passed from Stepper are Virtual Edges (if generated by Topology).
        # Wait, Stepper passes 'curr_edge_index' which might be ONLY virtual edges or mixed?
        # In EpisodeStepper._update_dynamic_topology:
        # It returns 'curr_edge_index' which is ONLY virtual edges generated for current anchors.
        # Yes, Topology.get_virtual_edges_for_subgraph returns ONLY virtual edges.
        # So we can trust edge_attr structure.
        
        # Check if edge_attr has enough channels
        if edge_attr.size(1) < 7:
            return torch.zeros(h_node.size(0), device=h_node.device)
            
        stt = edge_attr[:, 3]
        anchor_time = edge_attr[:, 4]
        anchor_type = edge_attr[:, 6]
        
        # Filter Negative Anchors (Type == -1)
        # Note: In Topology, anchor_value=1.0 for Positive. 
        # Negative anchors are -1.0? 
        # In Stepper L709: new_anchors_val is 1.0 or -1.0.
        # So yes, -1.0 is Negative.
        
        neg_mask = (anchor_type < -0.5)
        
        if not neg_mask.any():
            return torch.zeros(h_node.size(0), device=h_node.device)
            
        # Compute Delta T for each edge
        # Current time t_sim is per graph. We need to broadcast.
        # batch_idx is [N]. We need batch indices for EDGES.
        # edge_index[1] is target (Anchor). 
        # So edge_batch = batch_idx[edge_index[1]]
        
        dst_nodes = edge_index[1]
        edge_batch = batch_idx[dst_nodes]
        t_current = t_sim[edge_batch]
        
        # Delta T = Current Time - Anchor Discovery Time?
        # Or simply: Has water reached?
        # If I am at u, and I released poison at t=0.
        # It arrives at v at t = STT(u->v).
        # If at time t_current, v is CLEAN.
        # Then if t_current > STT(u->v), u is exonerated.
        # So we compare t_current vs STT.
        # (Assuming source starts at t=0).
        # Wait, if source starts at t_start?
        # We usually assume t=0 is the start of the event window.
        
        # Formula: Penalty = ReLU( t_current - STT * (1 + epsilon) )
        # Only for Negative edges
        
        penalty_edges = torch.zeros_like(stt)
        
        # Calculate violation for negative edges
        # violation = t_current - stt * (1 + eps)
        threshold = stt * (1.0 + self.epsilon_suppress)
        violation = t_current - threshold
        
        penalty_val = F.relu(violation)
        
        # Apply only to negative edges
        penalty_edges[neg_mask] = penalty_val[neg_mask]
        
        # Aggregate penalties to Source Node (u = edge_index[0])
        # We sum penalties from all negative anchors that refute u.
        src_nodes = edge_index[0]
        
        node_penalty = scatter_sum(penalty_edges, src_nodes, dim=0, dim_size=h_node.size(0))
        
        return self.lambda_suppress * node_penalty

    def compute_navigator_bias(self, h_node, edge_index, edge_attr, t_sim, batch_idx):
        """
        Scheme 2 & 3: Wave Front Chasing & Hub Attractor
        """
        bias = torch.zeros(h_node.size(0), device=h_node.device)
        
        if edge_attr.size(1) < 7:
            return bias
            
        stt = edge_attr[:, 3]
        anchor_type = edge_attr[:, 6]
        
        # --- Scheme 2: Wave Front Chasing ---
        if self.cfg.enable_wave_front_bias:
            # Only consider Positive Anchors (Type == 1)
            # We want to find sources that explain the positive observation "Just Now"
            # Or generally: If I see poison at v at time t_current.
            # The source u must be at distance STT approx t_current.
            
            pos_mask = (anchor_type > 0.5)
            
            if pos_mask.any():
                dst_nodes = edge_index[1]
                edge_batch = batch_idx[dst_nodes]
                t_current = t_sim[edge_batch]
                
                # Gaussian Kernel
                # Dist = |t_current - STT|
                # Score = exp( - Dist^2 / (2 * sigma^2) )
                
                # [ADAPTIVE SCALING FIX]
                # STT might be normalized (e.g. range [-1, 1] or [0, 1]).
                # delta_t is in physical minutes (e.g. 0, 45, 90).
                # We need to detect scale mismatch.
                
                # Heuristic: If STT is very small (mean < 1.0) and delta_t is large (> 10), 
                # we assume STT is normalized and delta_t needs to be scaled down, OR STT scaled up.
                # Or simply: Use a learnable scaler? No, keep it simple.
                
                # Check STT stats
                stt_mean = stt.mean()
                if stt_mean < 5.0 and t_current.mean() > 10.0:
                     # Likely mismatch.
                     # Option A: Normalize t_current to [0, 1]? Hard without t_max.
                     # Option B: Scale STT up to minutes? Hard without knowing factor.
                     # Option C: Use a separate sigma for normalized space?
                     
                     # Let's assume STT is normalized and use a small sigma (e.g. 0.1)
                     # But t_current is big.
                     # We must normalize t_current.
                     # t_max is usually 127 steps * 15 min? Or 127 minutes?
                     # In dataset.py: t_max = 127.
                     # t_sim is steps?
                     # Stepper: t_sim += delta_t (45.0). So t_sim is minutes.
                     # If STT is normalized, it's likely w.r.t max path length?
                     
                     # Safe Bet: Just use raw diff and let sigma handle it.
                     # BUT if diff is 100 and sigma is 15, exp is 0.
                     # If STT is 0.5 and t is 100, diff is 99.5. Exp is 0.
                     # If STT is 0.5 and t should be 0.5 (normalized time), then diff is 0.
                     
                     # Force t_current to be compatible if it seems off.
                     # If t_current is > 10 and stt < 1, maybe t_current should be scaled?
                     # Let's print warning once? No prints in forward.
                     pass

                diff = t_current - stt
                sigma = self.sigma_wave 
                
                # [ROBUSTNESS] If sigma is too small for the scale, we get sparse rewards.
                # If STT is normalized (0-1), sigma=15 is HUGE. All nodes get reward 1.0.
                # This matches our observation! Nav Bias Max=1.0.
                # If STT is 0 (or small) and t=0, diff=0, exp=1.
                # If t increases to 45, diff=45. exp(-45^2/...) ~ 0.
                # So only at t=0 we get huge bias?
                
                # Wait, Tracer showed Max=1.0 at Step 0. This is correct (t=0, stt=0).
                # But Sum=115088 (All nodes).
                # Because ALL nodes had STT=0 (due to bug).
                # Now that STT is fixed, only nodes with STT ~ 0 will get reward at t=0.
                # As t increases, nodes with STT ~ t will get reward.
                
                # So the logic is sound, PROVIDED STT and t are in same units.
                # If STT is seconds and t is minutes -> mismatch.
                # If STT is normalized and t is minutes -> mismatch.
                
                # Let's add a scaling factor 'time_scale' to config?
                # For now, assume consistent units (Minutes).
                # If STT is in seconds, we might need / 60.
                # If STT is 0.15 (Tracer), and it represents 15 min? Then scale is 100.
                
                wave_score = torch.exp( - (diff**2) / (2 * (sigma**2) + 1e-6) )
                
                # Apply mask
                wave_score = wave_score * pos_mask.float()
                
                # Aggregate to Source (u)
                # Max or Sum? 
                # If u explains multiple sensors, Sum is better.
                src_nodes = edge_index[0]
                wave_bias = scatter_sum(wave_score, src_nodes, dim=0, dim_size=h_node.size(0))
                
                bias += self.lambda_wave * wave_bias

        # --- Scheme 3: Hub Attractor ---
        if self.cfg.enable_hub_attractor:
            # Hub Score = Number of virtual outgoing edges (u -> v)
            # i.e. How many sensors does u influence?
            # This is simply degree centrality in the Virtual Graph.
            
            # [CRITICAL FIX] Must filter for Virtual Edges only!
            # Otherwise we are just computing physical degree centrality.
            is_virt = (anchor_type.abs() > 0.1)
            
            if is_virt.any():
                src_nodes = edge_index[0][is_virt]
                
                # Count edges per source
                hub_score = scatter_sum(torch.ones_like(src_nodes, dtype=torch.float), src_nodes, dim=0, dim_size=h_node.size(0))
                
                # Normalize?
                # Max per graph?
                max_hub, _ = scatter_max(hub_score, batch_idx, dim=0)
                max_hub_expanded = max_hub[batch_idx]
                hub_score_norm = hub_score / (max_hub_expanded + 1e-6)
                
                bias += self.lambda_hub * hub_score_norm
            
        return bias
